#!/usr/bin/env python3
"""Build the exact GTM Custom HTML loader from versioned source and config."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
CLIENT_PATH = ROOT / "storefront" / "vevo-growthbook" / "vevo-growthbook.js"
CONFIG_FIELDS = {
    "schemaVersion",
    "environment",
    "clientKey",
    "apiHost",
    "collectorUrl",
    "allowedHost",
    "gtmContainerId",
    "enableDevMode",
}


def validate_config(payload: object) -> dict:
    if not isinstance(payload, dict) or set(payload) != CONFIG_FIELDS:
        raise ValueError("config must use the exact storefront field set")
    if payload["schemaVersion"] != 1 or payload["environment"] != "preview":
        raise ValueError("only the reviewed Preview config can be built")
    if (
        not isinstance(payload["clientKey"], str)
        or not re.fullmatch(r"sdk-[A-Za-z0-9_-]{8,120}", payload["clientKey"])
        or "REPLACE" in payload["clientKey"]
    ):
        raise ValueError("invalid GrowthBook Preview client key")
    if payload["apiHost"] != "https://cdn.growthbook.io":
        raise ValueError("unexpected GrowthBook API host")
    if payload["allowedHost"] != "www.vevo.sk" or payload["gtmContainerId"] != "GTM-5ZB5LFGB":
        raise ValueError("unexpected VEVO storefront or GTM container")
    if payload["enableDevMode"] is not True:
        raise ValueError("Preview artifact requires enableDevMode=true")
    collector = urlparse(str(payload["collectorUrl"]))
    allowed_collector = bool(
        collector.hostname == "events-preview.vevo.sk"
        or re.fullmatch(
            r"[a-z0-9]+\.execute-api\.eu-central-1\.amazonaws\.com",
            collector.hostname or "",
        )
    )
    if (
        collector.scheme != "https"
        or not allowed_collector
        or collector.path != "/v1/events"
        or collector.params
        or collector.query
        or collector.fragment
        or collector.port
        or collector.username
        or collector.password
    ):
        raise ValueError("invalid Preview collector URL")
    return payload


def build_tag(
    config_path: Path,
    output_path: Path,
    *,
    client_key_override: str | None = None,
    collector_url_override: str | None = None,
) -> str:
    config_payload = json.loads(config_path.read_text(encoding="utf-8"))
    if client_key_override is not None or collector_url_override is not None:
        if not isinstance(config_payload, dict):
            raise ValueError("config must be a JSON object")
        config_payload = dict(config_payload)
    if client_key_override is not None:
        config_payload["clientKey"] = client_key_override
    if collector_url_override is not None:
        config_payload["collectorUrl"] = collector_url_override
    config = validate_config(config_payload)
    client = CLIENT_PATH.read_text(encoding="utf-8").strip()
    if "</script" in client.lower():
        raise ValueError("storefront client cannot be safely embedded in Custom HTML")
    config_json = json.dumps(config, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    artifact = (
        "<!-- Generated by scripts/build_vevo_growthbook_gtm_tag.py; do not edit in GTM. -->\n"
        "<script>\n"
        f"window.VEVO_GROWTHBOOK_CONFIG={config_json};\n"
        "</script>\n"
        "<script>\n"
        f"{client}\n"
        "</script>\n"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(artifact, encoding="utf-8", newline="\n")
    return hashlib.sha256(artifact.encode("utf-8")).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    digest = build_tag(
        args.config.resolve(),
        args.output.resolve(),
        client_key_override=os.getenv("VEVO_GROWTHBOOK_PREVIEW_CLIENT_KEY"),
        collector_url_override=os.getenv("VEVO_GROWTHBOOK_PREVIEW_COLLECTOR_URL"),
    )
    print(f"VEVO_GROWTHBOOK_GTM_SHA256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
